### ISSUE TITLE
[question] Skip does not work when import test case as `_`.

### ISSUE THREAD

**Issue by runkecheng** [onsi/ginkgo#874]
hello, I want to skip the case which in `pkg1`, I tried `ginkgo -skip="case1 "` and `ginkgo -skipPackage="pkg1"`, but both of them do not work.
```
import (
	"testing"

	"github.com/xxx/test/e2e/framework"
	_ "github.com/xxx/test/e2e/pkg1"
	_ "github.com/xxx/test/e2e/pkg2"
)

## pkg1
var _ = Describe("case1", func() {})
```

How should I do this? 

> Ginkgo Version is `v1.16.5`

**Comment by onsi** [comment]
hey @runkecheng `ginkgo -skip="case1"` should indeed work.  `-skipPackage` will not work as it only refers to the package that is being compiled - not any imported dependencies.

I do recommend upgrading to Ginkgo v2 soon - it includes features like [labels](https://onsi.github.io/ginkgo/#spec-labels) which will give you finer control over which specs to run/skip.

**Comment by onsi** [comment]
can you share some output from `ginkgo -v -skip="case1 "` - that really should be working...

**Comment by runkecheng** [comment]
I upgrade to the V2 version, but I still can't use the CLI to specify filtering criteria, the log shows that the incoming `LabelFilter` is a null value.
```
## I set `Scale` Label for one of It().
 ginkgo --label-filter="Scale" test/e2e/
=== RUN   TestE2E
Running Suite: Test Suite - xxx/test/e2e
[XXX] 
=======================================================================================================
Random Seed: 1641549215

Will run 5 of 5 specs


"SuiteConfig": {
      "RandomSeed": 1641549215,
      "RandomizeAllSpecs": false,
      "FocusStrings": null,
      "SkipStrings": null,
      "FocusFiles": null,
      "SkipFiles": null,
      "LabelFilter": "",
      "FailOnPending": false,
      "FailFast": false,
      "FlakeAttempts": 0,
      "EmitSpecProgress": false,
      "DryRun": false,
      "Timeout": 3600000000000,
      "OutputInterceptorMode": "",
      "ParallelProcess": 1,
      "ParallelTotal": 1,
      "ParallelHost": ""
    },
```

Fit () can work correctly, just CLI can't work.

**Comment by onsi** [comment]
any chance your repos are open source and i can take a look?

**Comment by runkecheng** [comment]
> any chance your repos are open source and i can take a look?

[here](https://github.com/runkecheng/radondb-mysql-kubernetes/tree/ginkgo_v2/test/e2e), Thank you.

**Comment by onsi** [comment]
ok thanks.  I don't think I understand _why_ this is happening but the flags aren't being parsed/aren't visible in your `e2e.go` file.   I see that you have an `e2e_test.go` file and an `e2e.go` file.  How Go does the packaging under the hood is subtle and sometimes confusing.  However, if you rename `e2e.go` to `e2e_X_test.go` (or merge it's contents into `e2e_test.go`) then the flags will be correctly parsed and things should work.

**Comment by runkecheng** [comment]
I merge e2e.go into e2e_test.go then the flag is parsed normally! thank you very much for your help.

**Comment by onsi** [comment]
great!  glad that helped.
